### ISSUE TITLE
Hit fatal exception (code 0x80000003) 

### ISSUE THREAD

**Issue by luis-reyes-a** [EpicGames/raddebugger#102]
Hit a fatal exception running latest commit. Last thing I did was "set next statement" a couple of lines before current statement. Entered a function and stepped through some code until it crashed with this info log.
Version 0.9.5 ALPHA, commit c02e033

Fatal Exception

A fatal exception (code 0x80000003) occurred. The process is terminating.

Call stack:
0. [0x7ff6db14c0cc] unw_pe_x64 +2332, unwind.c line 251
1. [0x7ff6db19e13e] df_push_unwind_from_thread +1566, df_core.c line 3638
2. [0x7ff6db1ae447] df_core_begin_frame +7015, df_core.c line 6685
3. [0x7ff6db25c0e6] update_and_render +3318, raddbg.c line 207
4. [0x7ff6db2736e6] entry_point +5654, raddbg.c line 524
5. [0x7ff6db0b245d] WinMain +877, raddbg_main.cpp line 348
6. [0x7ff6db2752ee] __scrt_common_main_seh +262, exe_common.inl line 288
7. [0x7ffb05427344] KERNEL32
8. [0x7ffb060c26b1] ntdll

**Comment by ryanfleury** [comment]
Looks like we were just asserting on a specific x64 PE unwinding opcode that we don't currently support. I've taken that assert out, so we won't unnecessarily crash in that case, you'll just have a broken callstack (although long-term ideally we fully support more unwinding cases). It's also possible that moving the RIP around is leading to some unexpected unwinding edge cases.

I've removed this assert locally; I am working on a pretty major commit so it isn't pushed yet, but will be soon.

**Comment by luis-reyes-a** [comment]
For future reference, are these crash reports useful when running the latest debug commit build or would you prefer to see this only from the latest release?

**Comment by ryanfleury** [comment]
Nope this was perfect, thanks!
