### ISSUE TITLE
Question: How to use --ipc

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGames/raddebugger#103]
I saw it in the --help section but it doesnt work. I tried with `raddbg --ipc open <filepath>`.
Does it require PID of the running instance of rdbg as well? (That too doesnt work).

**Comment by ryanfleury** [comment]
The `--ipc` stuff is currently unfinished, but I just tested `raddbg --ipc open <filepath>` and it did work, but it must be an absolute filepath, e.g.: `raddbg --ipc open C:/foo/bar/baz.txt`.

**Comment by MohitSethi99** [comment]
`run`, `step_into` works for me, but `open`, `toggle_breakpoint_cursor`, `goto_line` does not.
These are the only ones I tested.
Also, the client only processes the command when my cursor moves over the client window.

https://github.com/EpicGames/raddebugger/assets/29519295/1eeedecb-18ab-48c4-a734-6fb489e3a96d
