### ISSUE TITLE
C++11 containers support : std::map not able to show useful information 

### ISSUE THREAD

**Issue by kshanik** [EpicGames/raddebugger#105]
Is there any way it can decode and show key value pair information in watch window? Below information is not useful.

![image](https://github.com/EpicGames/raddebugger/assets/1548915/8af3ab1b-40de-4f30-b014-815f79e39ab9)

For below variable.

std::map<std::string, decl::var>            _props_map;

**Comment by ryanfleury** [comment]
There is no support for this at the moment, but this will be addressed with future NatVis support. That issue is already tracked via #38, so I'll close this one as a duplicate.
