### ISSUE TITLE
Exception 0xc0000005 on Attach

### ISSUE THREAD

**Issue by npiegdon** [EpicGames/raddebugger#110]
Built from master in a VS2022 prompt (about five minutes ago), launched, Shift+F6, found and selected my .exe in the list, this crash appears immediately and the debugger closes after clicking OK:

0. [0x7ff741659fa3] pe_intel_pdata_off_from_voff__binary_search +211, pe.c line 251
1. [0x7ff7416cb99e] unw_pe_x64 +174, unwind.c line 48
2. [0x7ff74172094e] df_push_unwind_from_thread +1566, df_core.c line 3632
3. [0x7ff741730c57] df_core_begin_frame +7015, df_core.c line 6679
4. [0x7ff7417dd2a5] update_and_render +3349, raddbg.c line 211
5. [0x7ff7417f4726] entry_point +5654, raddbg.c line 528
6. [0x7ff74163245d] WinMain +877, raddbg_main.cpp line 348
7. [0x7ff7417f633e] __scrt_common_main_seh +262, exe_common.inl line 288
8. [0x7ffea4fa7344] KERNEL32
9. [0x7ffea51426b1] ntdll

The app I was trying to attach was [this](https://synthesia.app/get?platform=win_sa&version=10.9) zip, with the contents extracted to a folder.

No debug symbols present.  (Are they required?  Is that the bug?)

**Comment by ryanfleury** [comment]
Nope - looks like this EXE in particular exposed an edge case where the binary's header specified a range for unwinding information that was not within the valid range of the file. Fixed in 94b1888073c342d128a591ebd1b39f8b7860f4cd, you should be able to attach to that EXE now.
