### ISSUE TITLE
All local values are `0` with certain ~LLVM PDBs

### ISSUE THREAD

**Issue by hotgluebanjo** [EpicGames/raddebugger#111]
Clang MinGW, Zig CC and rustc PDBs display zero for nonzero locals (in both locals and watch):

![image](https://github.com/EpicGames/raddebugger/assets/66244111/a59c7c65-e015-48cb-b102-aaa322b668da)

Should be working, right? WinDbg handles them with no problems. They load and convert fine for the most part, bar when they inexplicably don't and a recompile is needed.

This issue doesn't affect MSVC PDBs obviously. Nor those generated by an equivalent Odin program, interestingly:

![image](https://github.com/EpicGames/raddebugger/assets/66244111/84a9dcef-4067-4de5-acbd-e2d17803dec9)

Related: #4

Not sure how it's looking for files, so apologies for the lack of helpfulness.

[repro.zip](https://github.com/EpicGames/raddebugger/files/14037505/repro.zip)

---

Also tentatively mentioning: rapidly hitting `Alt+Enter` to go into full screen caused a freeze for me. Might not be able to reproduce; froze entire computer.

**Comment by ryanfleury** [comment]
Yeah, should be working, probably just exposing a new/different location info case. I’ll take a look today.

**Comment by ryanfleury** [comment]
Fixed in 69f77456b8fceaac0b31937894886cd06acd1817. Let me know if you run into any other issues. You may need to delete your `.raddbg` files to see it fixed.

**Comment by hotgluebanjo** [comment]
Working perfectly with Zig CC for me. No freezing either. Seems that was from the menu bar. Thanks; incredible work!

#4 should stay open still. A note for people searching: PDBs from these compilers may not handle relative paths correctly.

**Comment by hotgluebanjo** [comment]
LLVM-MingGW Clang and rustc are working as of now.
