### ISSUE TITLE
Empty .raddbg file is not handled

### ISSUE THREAD

**Issue by mistymntncop** [EpicGames/raddebugger#117]
When the .RADDBG file exists but has no contents debugging doesn't work. Probably should try to regenerate the file if it is empty.

Steps to reproduce:
1. Compile any program. e.g. test.c
```
#include <stdio.h>
#include <stdint.h>

int main(void) {
    return 0;
}
```

2. Create an empty RADDBG file for the program. e.g.
echo. 2> test.raddbg

Obviously debugging information will not be available if you try debugging the program again.

**Comment by ryanfleury** [comment]
Fixed in f69176ee4ebdaea9358f8c6465a1cbc45ecdd1a4.
