### ISSUE TITLE
Fatal exception thrown

### ISSUE THREAD

**Issue by luis-reyes-a** [EpicGames/raddebugger#121]
Hit another assert I think. What I was doing was right clicking in the source file view to press "Run to Line" while program was running.
Currently on latest commit 7355389

Fatal Exception

A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
0. [0x7ff65eaab6fa] df_eval_watch_view_build +12746, df_views.c line 992
1. [0x7ff65ea34844] df_view_ui_Watch +132, df_views.c line 6465
2. [0x7ff65ea77774] df_window_update_and_render +143940, df_gfx.c line 5594
3. [0x7ff65eab4991] update_and_render +4369, raddbg.c line 286
4. [0x7ff65eacbe57] entry_point +5671, raddbg.c line 580
5. [0x7ff65e90245d] WinMain +877, raddbg_main.cpp line 350
6. [0x7ff65eacda6e] __scrt_common_main_seh +262, exe_common.inl line 288
7. [0x7ffb33787344] KERNEL32
8. [0x7ffb340626b1] ntdll

**Comment by ryanfleury** [comment]
Doesn’t look like an assertion, I think this might be because of missing type information being poorly handled by the new watch window change visualization code. Do you have more information on what was in the watch window?

**Comment by ryanfleury** [comment]
I think this should be fixed by 28e258b5dc0bb11f0ccb0f46a079f41ad43665c3, but let me know about the more info & if it happens again.

**Comment by luis-reyes-a** [comment]
Hey Ryan, I pulled latest version and have not been able to reproduce the crash.
Also, I'm curious how you're generating the crash screen, I just assumed it was a custom assert macro that would make a window.
Thanks
