### ISSUE TITLE
Spaces seem to delimit command line arguments

### ISSUE THREAD

**Issue by achalpandeyy** [EpicGames/raddebugger#122]
I have a simple C++ program
```
#include <stdio.h>

int main(int argc, char **argv)
{
    printf("argc: %i\n", argc);
    for (int i = 0; i < argc; ++i)
    {
        printf("argv[%i]: %s\n", i, argv[i]);
    }
    return 0;
}
```
which I compile as `cl /nologo /Zi main.cpp`

When I run it:
```
E:\>main.exe -a something_here -b  "something here with spaces"
argc: 5
argv[0]: main.exe
argv[1]: -a
argv[2]: something_here
argv[3]: -b
argv[4]: something here with spaces
```

While in raddebugger
![bug](https://github.com/EpicGames/raddebugger/assets/35342732/214d992b-2cee-407c-84cc-9d0d4cd1f4ec)

**Comment by ryanfleury** [comment]
Fixed in 1ade5e44fac4272f7f9a3e0a9bd4714f021b0964. I've also fixed the debugger's lack of support for serializing double quotes in target arguments (and other places) in 3fd9014c20461c1e7fa4aec6f7aab93117c27b65.
