### ISSUE TITLE
Fatal exception occured

### ISSUE THREAD

**Issue by luis-reyes-a** [EpicGames/raddebugger#123]
Not sure why I keep hitting these... Below is a screenshot of what I was doing when it occurred. I hit a breakpoint then removed the breakpoint and continued to run my process and while it was running it crashed (it may have been as soon as I pressed continue).
Running commit 28e258b

Fatal Exception

A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
0. [0x7ff71a51ddef] f_push_run_from_string +255, font_cache.c line 586
1. [0x7ff71a51f99d] f_dim_from_tag_size_string +237, font_cache.c line 950
2. [0x7ff71a5f55d2] df_code_slice +11586, df_gfx.c line 9578
3. [0x7ff71a5fbbdc] df_code_slicef +332, df_gfx.c line 10330
4. [0x7ff71a59736c] df_view_ui_Output +8076, df_views.c line 7020
5. [0x7ff71a5d7ae4] df_window_update_and_render +143940, df_gfx.c line 5594
6. [0x7ff71a614d01] update_and_render +4369, raddbg.c line 286
7. [0x7ff71a62c1c7] entry_point +5671, raddbg.c line 580
8. [0x7ff71a46245d] WinMain +877, raddbg_main.cpp line 350
9. [0x7ff71a62ddde] __scrt_common_main_seh +262, exe_common.inl line 288
10. [0x7ffecf157344] KERNEL32
11. [0x7ffecfa226b1] ntdll

![raddbg_snapshot](https://github.com/EpicGames/raddebugger/assets/29178817/71ceaee6-5934-4dfe-9f01-a3c4a3dbbff1)

**Comment by ryanfleury** [comment]
With this message box pulled up, can you attach a debugger to RADDBG, and see what `string` is, in the top callstack frame, inside of `f_push_run_from_string`?

**Comment by luis-reyes-a** [comment]
I can't seem to reproduce it running through visual studio. I've also noticed that spamming OutputDebugStringA seems to make the window flicker and reset the view to the top of the window. Pausing execution seems to give it time to "catch up" and it'll fix itself. Here I ran it for a while and it took a while to normalize

(Please mute audio, may be loud for you. Didn't notice I was capturing sound)
https://github.com/EpicGames/raddebugger/assets/29178817/06b118ff-9ddd-48c9-a221-6178cbccebab

**Comment by ryanfleury** [comment]
You should be able to run outside of VS, then just attach after the message box is opened - you should be within the callstack of the crash itself.

**Comment by ryanfleury** [comment]
Alright, I reproduced this on my end! Hang tight, I'll get this fixed.

**Comment by ryanfleury** [comment]
This crash should be fixed in d1fde3c9088dcca1b178a0920aa5bfb5fe060695.

**Comment by luis-reyes-a** [comment]
Awesome! I didn't know you could attach a debugger to an already running instance. I'll keep that in mind if I get another crash. Thanks!
