### ISSUE TITLE
scripting and extending the debugger

### ISSUE THREAD

**Issue by duaneellissd** [EpicGames/raddebugger#132]
many debuggers have a script language or some tupe of interactive prompt

please consider using a well known first class script language or interactive prompt

for example consider python because you can use pyqt to talk to the gui screen, create gui things with buttons and sliders etc
 another example is in the embedded world one might use a powersupply that you can command on/off via socket or serial port [think pyserial]

and have you thought about remote access - ie gdbremote or gdbserver? which is a wrapper around the unix ptrace function and an rpc language that is what allows one to do jtag debugging of embedded systems.

in your world think of remoting into some other lib]nux platform to debug something

**Comment by ryanfleury** [comment]
We have long-term plans for both debugger interaction via APIs and/or IPC protocols, which can be wrapped in whatever someone wants externally, and also plans for remote debugging. We'll likely not be wrapping existing third-party systems for doing so.
