### ISSUE TITLE
Program Crashes when bitmap size is huge

### ISSUE THREAD

**Issue by alexgwalley** [EpicGames/raddebugger#136]
The program crashes when a bitmap size is too big in the watch window. I found this out when some garbage data was being written into a struct that I was reading the bitmap's width and height from.

![image](https://github.com/EpicGames/raddebugger/assets/10475866/a6f2c343-a39d-4982-9af7-95f6cf611dcb)

Perhaps just adding a cap to it would be fine? Not sure how you would like to handle this.

[Window Title]
Fatal Exception

[Content]
A fatal exception (code 0x80000003) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
0. [0x7ff7350125c1] arena_alloc__sized +321, base_arena.c line 44
1. [0x7ff7350bd145] ctrl_mem_stream_thread__entry_point +1317, ctrl_core.c line 3255
2. [0x7ff7350272b8] w32_thread_base +56, os_core_win32.c line 173
3. [0x7ff858ca7344] KERNEL32
4. [0x7ff85abe26b1] ntdll

[Close]

**Comment by ryanfleury** [comment]
I've added caps in f03f3e4421470f9068f24ac48a1cf3788c1a9a05, so this should no longer happen. The debugger can't upload & render textures of extraordinarily large size anyways, and so it doesn't really make sense to do anything else.
