### ISSUE TITLE
[Jai] Procedure source code mapping not working?

### ISSUE THREAD

**Issue by rytc** [EpicGames/raddebugger#138]
Not sure what's going on but it seems like source code mapping with jai isn't working properly? First few line of a procedure seem to be fine, but after a certain point I can't break or step through the lines. Works ok with other debuggers

![image](https://github.com/EpicGames/raddebugger/assets/31718059/2bf9a7a0-3def-41e3-b4b8-5aad7fc7e047)

![image](https://github.com/EpicGames/raddebugger/assets/31718059/2d0f791f-3be2-419c-ac25-f31035bb0766)

**Comment by rytc** [comment]
If you have access to the beta, the included Invaders example does it in the `invader_fire_bullet()` procedure in `invaders.jai` as well as a couple of other places in there. It seems to be fine for smaller single file programs like the how_tos and my own little random test case.

**Comment by ryanfleury** [comment]
This should be fixed in 390aab2699201a35922591941f700de476a0075d. Let me know if you run into anything like this again.
