### ISSUE TITLE
Execution halted at wrong line when breakpoint set. 

### ISSUE THREAD

**Issue by jristic** [EpicGames/raddebugger#141]
Version: 0.9.8 ALPHA

When setting a breakpoint then running my program, I'm getting a breakpoint hit where I did not set one:
![image](https://github.com/EpicGames/raddebugger/assets/1256627/fc199631-3169-4f10-ad1b-836368fe6f42)

Note that the breakpoint is set at win32_d3d12_main.cpp line 378 but the callstack shows program execution stopped at 659. 

Source and prebuilt binaries for reproing:
https://drive.google.com/file/d/1KAi_W59tVLaWrGi-6HqATXM4KYHgZrHS/view?usp=sharing

**Comment by ryanfleury** [comment]
This was the same bug as in #138, as it turns out. This has been fixed in 390aab2699201a35922591941f700de476a0075d. Let me know if you run into the same issue again. To see the changes, you'll need to rebuild your executable and/or delete your existing RADDBG files.

**Comment by jristic** [comment]
Awesome, thank you! It's been a great debugger otherwise.
