### ISSUE TITLE
How to open a project.

### ISSUE THREAD

**Issue by Stanlyhalo** [EpicGames/raddebugger#146]
I'm trying out RAD Debugger, and I was wondering if I can open up visual studio based projects and/or solutions. I know this tool is more of a debugger, but I wanna see if I can use it as an editor. Is this possible? Or would I need to make some other file format? Is it even possible to edit files using this or is this not meant for that?

**Comment by ryanfleury** [comment]
The debugger does not have any code editing features, and has no interoperability with Visual Studio solution files. All debugging project information is stored in `raddbg_profile` files, mainly in form of target executable paths (with other per-target information, like executable arguments, working directory, and so on), breakpoints, watch pins, and so on.
