### ISSUE TITLE
Crash when address sanitizer is enabled

### ISSUE THREAD

**Issue by nukoseer** [EpicGames/raddebugger#15]
When I compile my program with `/fsanitize=address` option, it directly crashes when started in raddbg. raddbg directly jumps to address sanitizer source before it reaches to the main function and `Main thread interrupted - 0xc0000005` message appears under the screen. I remember `0xc0000005` means `access violation` but it occurs before the main function somehow. I tested it with 2 diffent programs and both of them behaved same when `/fsanitize=address` is set. I also checked them without debugger and with the Visual Studio Debugger for reference and there was no problem in those cases.

**Comment by ryanfleury** [comment]
Thanks for reporting this. It looks like this has to do with ASan's strategy of using exception handlers to on-demand map pages. I'm going to look into the expected debugger strategy here. In the meantime, if you open up the Exception Filters view ([image](https://github.com/EpicGames/raddebugger/assets/12454169/49995a47-64d5-4a0d-b2ac-ddc67dcd6a5b)), you can disable the `0xc0000005` exception code. When testing, I hit a few more unexpected breakpoints (e.g. in `malloc`), so there is still some investigation & fixing I need to do, but this should at least get you into your program.

**Comment by nukoseer** [comment]
Yes, it worked when I disabled access violation exception. Thank you!

**Comment by ryanfleury** [comment]
As of 42993b3fb0ff52d00f6deb964a3e48fd0328402b, the exceptions used by ASan to on-demand map pages in their "shadow address space" will be silently filtered by the debugger. Let me know if you run into any further issues with this.
