### ISSUE TITLE
Releasing ALT while typing in watch window moves focus to menu bar

### ISSUE THREAD

**Issue by Cr0wn24** [EpicGames/raddebugger#16]
https://github.com/EpicGames/raddebugger/assets/61281897/78874d06-7dd7-49df-8493-97d5c1ec972b

edit: I have a nordic keyboard layout where I have to press the ALT key in order to type square brackets, hence why I type square brackets in the video.

**Comment by ryanfleury** [comment]
This should be fixed in 813554fa62751d19faf1f280c4c1c6af214f43d0 and 76b2facbf4ebafbb1b9fb359703c46e6fd73b314. The debugger now properly distinguishes between Alt and AltGr, and detects Alt-based text input, and short-circuits menu bar operations in such cases.
