### ISSUE TITLE
UI does not render / black screen

### ISSUE THREAD

**Issue by zpl-zak** [EpicGames/raddebugger#17]
Hey,

Congratulations on getting this out! Unfortunately, I was not able to run the debugger on my end. The viewport is blank, with occasional UI elements popping in on mouse hover.

Unfortunately, I only have a few details to provide, but please let me know if you need any specifics!

## Specs
Windows 11 - 22631.3007
NVIDIA GeForce RTX 3080 Ti - driver 546.33

## Media

https://github.com/EpicGames/raddebugger/assets/9026786/f5a00849-0065-4035-835b-9cfe5ab1135e

Thank you!

**Comment by mmozeiko** [comment]
Can you force debug layer and run under debugger?
You can do that by enabling it in DirectX Control Panel (dxcpl.exe) for specific application exe or by editing code.

**Comment by nickrolfe** [comment]
I see the same behaviour as OP's video. I have the _exact_ same Windows version, Nvidia card, and Nvidia driver version.

Here's the output from the D3D11 debug layer:
```
D3D11 WARNING: Process is terminating. Using simple reporting. Please call ReportLiveObjects() at runtime for standard reporting. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: Live Producer at 0x000001A28DC19420, Refcount: 37. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A291FA6C90, Refcount: 2. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2961F5720, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2961A2B70, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296204C90, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296204ED0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296205110, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296205350, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962055D0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296205810, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296205C00, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296205E40, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296206080, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962062C0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962086F0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296232910, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962307B0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29622EE00, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296231EF0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29627B7C0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29627D5D0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962B1A90, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962C63F0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962D26D0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962D33C0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962D1E30, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962CFAF0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962EF0E0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962F8930, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962F8D50, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2962CAE20, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29632C7E0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2920D8430, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2920DB320, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2920D7FF0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296388E60, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2963815B0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296388420, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2963819F0, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296390E20, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29638D390, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296392220, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2963924F0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29638A050, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2963930E0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A2963933B0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296393FA0, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A296394240, Refcount: 1. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: 	Live Object at 0x000001A29202E340, Refcount: 0. [ STATE_CREATION WARNING #0: UNKNOWN]
D3D11 WARNING: Live                         Object :     48 [ STATE_CREATION WARNING #0: UNKNOWN]
```

**Comment by ryanfleury** [comment]
None of that looks suspicious to me; I've just added a `--force_d3d11_software` flag you can pass to `raddbg` from command line in ca8727c4afdfce24f62b701e3f82c79006a16297, which will ask for a software D3D11 driver. It's very slow, but it might help us get to the bottom of this issue.

If you pull from the `dev` branch, build, and then pass `--force_d3d11_software` to `raddbg`, do you get the same result?

If you don't want to build locally then I've attached a build here also:
[raddbg.zip](https://github.com/EpicGames/raddebugger/files/13924789/raddbg.zip)

**Comment by zpl-zak** [comment]
Running the debug build with D3D11 dbg layer enabled in the debugger does not give me any warnings or logs that would look out of place.

I've now tested the attached build with `--force_d3d11_software` passed, the issue persists.

**Comment by LTGL2007** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/148474487/eee26cda-abcd-4987-bd75-cb8c2bf13600)
it is not completely black, when hovering on buttons you do have the animation. but the overall screen is black.

**Comment by ryanfleury** [comment]
Is it possible for someone who is experiencing this issue to provide a [RenderDoc](https://renderdoc.org/) capture? That might also provide some useful information.

**Comment by zpl-zak** [comment]
> Is it possible for someone who is experiencing this issue to provide a [RenderDoc](https://renderdoc.org/) capture? That might also provide some useful information.

Here is the capture (had to ZIP it for the attachment)

[raddbg_cap.zip](https://github.com/EpicGames/raddebugger/files/13924878/raddbg_cap.zip)

**Comment by LTGL2007** [comment]
> > Is it possible for someone who is experiencing this issue to provide a [RenderDoc](https://renderdoc.org/) capture? That might also provide some useful information.
> 
> Here is the capture (had to ZIP it for the attachment)
> 


[doc.zip](https://github.com/EpicGames/raddebugger/files/13924902/doc.zip)

**Comment by NewbLuck** [comment]
Same issue, noticed that the default.raddbg_user in the appdata directory for raddbg has every color in it set to 0x00000000.  Tested setting plain_text to 0xFFFFFFFF and suddenly I had visible text.

**Comment by zpl-zak** [comment]
From RenderDoc capture it does look like colors are indeed coming into shader as zeroes.

**Comment by ryanfleury** [comment]
Oh boy. Reproduced... Stand by.

**Comment by LTGL2007** [comment]
as a temp solution:
in AppData\Roaming\raddbg paste this:
colors:
{
  plain_text:                    0xe5e5e5ff
  plain_background:              0x3333337f
  plain_border:                  0xffffff19
  plain_overlay:                 0xffffff33
  code_default:                  0xe5e5e5ff
  code_function:                 0x7fcc99ff
  code_type:                     0x66b2e5ff
  code_local:                    0xfe9548ff
  code_keyword:                  0xf7bf5eff
  code_symbol:                   0x994c32ff
  code_numeric:                  0x4ce54cff
  code_string:                   0xe5cc66ff
  code_meta:                     0xe54c4cff
  code_comment:                  0x7f7f7fff
  line_info_0:                   0x3f72993f
  line_info_1:                   0x3f72994c
  line_info_2:                   0x3f729972
  line_info_3:                   0x3f72997f
  alt_text:                      0xe5e5e5ff
  alt_background:                0x42474c7f
  alt_border:                    0xffffff19
  alt_overlay:                   0xffffff33
  tab_inactive:                  0x42474c7f
  tab_active:                    0xa87a4c99
  entity_background:             0x4293cc99
  query_bar:                     0x8e2d4ccc
  weak_text:                     0xffffff7f
  text_selection:                0x99ccff4c
  cursor:                        0x66e566e5
  highlight_0:                   0xb27219ff
  highlight_1:                   0x327f19ff
  success_text:                  0xe5e5e5ff
  success_background:            0x32b219ff
  success_border:                0xffffff33
  failure_text:                  0xe5e5e5ff
  failure_background:            0xb23219ff
  failure_border:                0xffffff33
  action_text:                   0xffffffff
  action_background:             0x327fb2ff
  action_border:                 0xffffff33
  drop_site_overlay:             0xffffff0c
  thread_0:                      0xffcb7fff
  thread_1:                      0xb2ff65ff
  thread_2:                      0xff99e5ff
  thread_3:                      0x6598ffff
  thread_4:                      0x65ffcbff
  thread_5:                      0xff9819ff
  thread_6:                      0x9932ffff
  thread_7:                      0x65ff4cff
  thread_unwound:                0xb2ccd8ff
  inactive_panel_overlay:        0x0000003f
  drop_shadow:                   0x0000007f
}

**Comment by ryanfleury** [comment]
Here I was thinking it was the renderer... turns out it has to do with what I changed earlier today. Who would've guessed :')

**Comment by ryanfleury** [comment]
Sorry about that all. Just overwrote the 0.9.1-alpha release, since the debugger was unusable as long was this in there, so you can redownload [here](https://github.com/EpicGames/raddebugger/releases/download/v0.9.1-alpha/raddbg.zip).

**Comment by IAmVoran** [comment]
As a note to anyone who experienced this even after redownloading; delete the config in %appdata%\raddbg and it'll work.

**Comment by ghostway0** [comment]
I am having the same problem. Although, colors do seem to load, and when I click the screen I get some logs from OpenGL. Has anyone encountered this or should I just continue debugging?

**Comment by ryanfleury** [comment]
@ghostway0 This is very likely not the same bug. If you’re using OpenGL, I imagine you’re trying a Linux build? In that case, Linux is not supported yet, so the renderer hasn’t been developed to the same degree that it has on Windows.

**Comment by ghostway0** [comment]
Yes I'm on Linux. Was the OpenGL renderer developed recently? It seemed as if it was trying to load buffers because the logs said something about buffers using video memory. I guess I'll stop discussing it here, debug a little and come back with an issue. Or are you saying it's not worthwhile yet?

**Comment by ryanfleury** [comment]
It's definitely not worthwhile yet. Once we have Linux support officially up and running, we'll want to make sure that issue is resolved, but it might be fixed just by the time the first pass of the port is actually done.

**Comment by slendidev** [comment]
I got this working with the following patch: https://paste.slendi.dev/Gv2gHX.txt, @ghostway0 do you think you can try this out and see if it works for you? Just run `git apply` on the patch. Thanks.

**Comment by ghostway0** [comment]
works! amazing @slendidev .
