### ISSUE TITLE
Access violation when closing panel

### ISSUE THREAD

**Issue by nico-abram** [EpicGames/raddebugger#18]
It only happens in some specific panel configurations.

I can consistently trigger it from the default configuration by deleting the following panels: Targets, Scheduler, Disasm, Output/Watch/Memory and then finally trying to delete the main panel:
![imagen](https://github.com/EpicGames/raddebugger/assets/24706838/e19d83f0-3cf4-4159-b98c-837ec4453b5d)
![imagen](https://github.com/EpicGames/raddebugger/assets/24706838/c6a84d44-ef23-48c5-82b1-25b22eb1420b)

I'm attaching a test configuration (Added an extension since github requires it before it lets me upload the file)
[default.raddbg_user.txt](https://github.com/EpicGames/raddebugger/files/13926930/default.raddbg_user.txt)

**Comment by ryanfleury** [comment]
Fixed in d382053500b28785df55c67527253a20373a1692.
