### ISSUE TITLE
Ctrl + C doesn't work on source files while Find text is opened (Ctrl-F)

### ISSUE THREAD

**Issue by DevAgu93** [EpicGames/raddebugger#20]
Only copying from the context menu works.

https://github.com/EpicGames/raddebugger/assets/63572671/258d8bd5-b016-4ef8-8ee4-a72321eb8257

**Comment by ryanfleury** [comment]
This is working as I originally intended; pressing Ctrl+C in this context is copying the (empty) selection from the "Find Text" search field, which has keyboard focus (visualized by the red cursor color in the source view). To switch focus back to the source view, you need to hit Escape to cancel the search, then copy what you want, then go back to the search and paste.

What I might do to match user expectations more here is introduce the ability to select either the query bar *or* the panel's contents, while both are in-flight, by clicking on either.

**Comment by DevAgu93** [comment]
That, and also being able to select text by double clicking 😁

**Comment by ryanfleury** [comment]
Yep, on [the list](https://github.com/EpicGames/raddebugger/blob/dev/src/raddbg/raddbg.h#L190) :)

**Comment by ryanfleury** [comment]
Just updating this thread to reference:

> What I might do to match user expectations more here is introduce the ability to select either the query bar or the panel's contents, while both are in-flight, by clicking on either.

This is now done as of e56eb077d0821e13dbf87c6f3941ee956013291f.
