### ISSUE TITLE
Can't set breakpoint on where the cursor stands.

### ISSUE THREAD

**Issue by DevAgu93** [EpicGames/raddebugger#22]
When trying to click on the stepping cursor, I can't set a breakpoint there:

https://github.com/EpicGames/raddebugger/assets/63572671/89bca616-85f1-4af4-9d26-63386ceef95d

**Comment by ryanfleury** [comment]
The way to do this currently is to either use the default binding of F9 (after closing the query bar), or to right-click the line and click "Place Breakpoint". I might end up splitting the columns in the future, such that the breakpoint column is always separate from the instruction pointer column, but there is kind of an unavoidable problem here in any case, which is that individual source lines tend to have a lot of information, and so you can't reserve the most compressed inputs (e.g. left-mouse-click) for everything you might want to do on any line.
