### ISSUE TITLE
Breakpoint and stepping doesn't work in the source file. Goes to disassembly.

### ISSUE THREAD

**Issue by Scr3amer** [EpicGames/raddebugger#26]
Hello there !
I tested today your debugger, it is a promising project that reminds me of RemedyBG but with a way bigger scope.

I had one big issue today:

I tried it on a dummy project I had at home that I compiled using mstorjso llvm-clang-mingw-ucrt toolchain 16.0.6 and when I put a breakpoint in the source code, it gets reached but opens the dissasm window instead of the source code. And when I step in the code, it keeps stepping in the ASM instead of the source code.

I checked and the PDB was properly loaded. Am I missing ? Is there a source-mode stepping we need to activate ?

Cheers,
Scr3amer

**Comment by ryanfleury** [comment]
If the PDB was loaded (meaning first converted to a RADDBG file - you should see `your_exe_name.raddbg` next to `your_exe_name.pdb`) successfully, then the debugger will do line snapping & stepping first. Can you send me data about the dummy project - maybe the EXE/PDB/RADDBG file, or if you are willing, the source code? (And if the dummy project is larger, can you try isolating the same problem in a stripped down version, e.g. a "Hello World" executable built with the same toolchain, where the debugger behaves the same way?)

Thanks!

**Comment by Healium** [comment]
I had the same problem. What fixed it for me was to delete the "%appdata%/raddbg" folder and use version 0.9.1.

**Comment by Scr3amer** [comment]
@ryanfleury First of all thank you for the quick reply. You guys are working on Saturday :D ? Or you love so much the project you are giving free time during the week end ^^ ?

Regarding the issue I digged a little bit more and I am basically a duplicate of https://github.com/EpicGames/raddebugger/issues/32

Funny enough it was posted only 4 hours ago :D. I was lucky with the timing because it didn't cross my mind that could be the issue. I still don't understand how come the RADDBG file was generated yet not used.

I compiled using the /pdbaltpath linker option to specify a relative PDB path.
And when I moved the debugger .exe in the same folder as the .exe and .pdb it worked flawlessly.

**Comment by ryanfleury** [comment]
Definitely in love with the project, but just want to get it solid and resolve the worst of the issues quickly to ensure it gets closer for more people to being a viable daily debugging option!

That makes a *lot* of sense. I appreciate you looking into this! I will resolve those relative PDB path issues soon.

**Comment by xbowzone** [comment]
This happens again now with llvm mingw toolchain. It doesnt create rdi. Works just fine for msvc however. Last version that was without this problem is 0.9.21 which I'm sticking with. pdb file is properly created and works with 0.9.21 but not newer versions.

**Comment by mmozeiko** [comment]
I just tried using llvm-mingw from 20260407 on simple example and it worked for me. How are you compiling your code?

I did this: `x86_64-w64-mingw32-clang++.exe -g -gcodeview -Wl,-pdb= test.cpp` - it produces test.pdb, and then when debugger runs it creates test.rdi. Try deleting .pdb/rdi files before running this and restart debugger just in case - it sometimes wrongly caches old rdi file info in memory.

**Comment by xbowzone** [comment]
> I just tried using llvm-mingw from 20260407 on simple example and it worked for me. How are you compiling your code?
> 
> I did this: `x86_64-w64-mingw32-clang++.exe -g -gcodeview -Wl,-pdb= test.cpp` - it produces test.pdb, and then when debugger runs it creates test.rdi. Try deleting .pdb/rdi files before running this and restart debugger just in case - it sometimes wrongly caches old rdi file info in memory.

I did: cc -g3 -Og -gcodeview -Wl,--pdb= -Wall -mwindows --target=x86_64-w64-windows-gnu -I./include -L./lib -lraylib -lopengl32 -lgdi32 -lwinmm main.c -o main.exe

The code I tried on is rayllib [raylib-5.5_win64_mingw-w64.zip] downloaded official compiled release from: https://github.com/raysan5/raylib/releases/tag/5.5
And I just tried on basic window eg here https://github.com/raysan5/raylib 
Same llvm mingw version as yours. And yes, I delete and reproduce exe, pdb always. And raddbg appdata folder too. Just to get potentially old data issue out of the way each time. 
And same thing that I did above works with version 0.9.21 just fine.

**Comment by mmozeiko** [comment]
Ah, what most likely happens here is that raylib comes with dwarf debug info. While dwarf debug info is not yet fully supported in raddbg, it tries to use it first and fails (probably conversion crashes). To workaround this, try building by stripping debug info - append `-Wl,-s` argument. Or alternatively run `strip.exe --strip-debug main.exe` utility after your build step. Either of these things will remove dwarf debug info, but leave pdb file, so raddbg will be able to load it.

**Comment by xbowzone** [comment]
> Ah, what most likely happens here is that raylib comes with dwarf debug info. While dwarf debug info is not yet fully supported in raddbg, it tries to use it first and fails (probably conversion crashes). To workaround this, try building by stripping debug info - append `-Wl,-s` argument. Or alternatively run `strip.exe --strip-debug main.exe` utility after your build step. Either of these things will remove dwarf debug info, but leave pdb file, so raddbg will be able to load it.

Thanks. That was it.
