### ISSUE TITLE
Crash when dragging down memory window too far

### ISSUE THREAD

**Issue by IvyTheGreat01** [EpicGames/raddebugger#28]
Thanks for making this cool debugger and open sourcing it! Here's a ui bug I found.

Current build: #27, Win 10

Step 1: Open the memory window and scroll down a little.
Step 2: Drag down until the memory part dissappears.

![image](https://github.com/EpicGames/raddebugger/assets/46989884/ea257136-5755-44b7-926e-b917815d15b9)
![image](https://github.com/EpicGames/raddebugger/assets/46989884/0c3d00ea-dc90-40df-929f-f540c1a70bfe)

**Comment by ryanfleury** [comment]
Thanks! Fixed in bcdc2f3026b88782665ba30650a5f4add98f0ea2.
