### ISSUE TITLE
"a bad, rare bug" hit while stepping

### ISSUE THREAD

**Issue by vfig** [EpicGames/raddebugger#29]
i was stepping through a program of mine, trying to identify a bug in my code (a tiny program compiled with vs2022), when i got the following error message:

"a bad, rare bug that Jeff found has been detected to occur - attach with debugger now".

![image](https://github.com/EpicGames/raddebugger/assets/81129/a2f77b02-fd9d-4fb6-b4da-69a62a3c9c3c)

i cant really provide reproduction steps—i cant say what i was doing more precisely than "stepping through and looking at local variables"—but for the moment i still have this session open at this message. do you want a crash dump? or should i attach vs2022 to raddbg and collect some info?

**Comment by ryanfleury** [comment]
Wow, I'm glad I left that in there, it has been a long time since I've seen that! Yes, can you please .zip up a crash dump, along with the `raddbg.exe` you are using, and the `raddbg.pdb` you are using? It'd also help to see the locals window of the debugger.

The more information the better, here, so if you are okay with sending the program itself (+ PDB & RADDBG files), source code, etc., the more easily I'll be able to try and reproduce and find out what happened.

**Comment by vfig** [comment]
if i just hit OK on this dialog without attaching, will it save a crash dump?

**Comment by ryanfleury** [comment]
No, it won't, you'll want to attach with e.g. Visual Studio and save a dump file from there.

**Comment by vfig** [comment]
raddbg was built with default options from 5410fac.

screenshot (showing locals); raddbg exe and pdb; all the files from the target; and crash dump saved from vs2022 are all in:

https://www.dropbox.com/scl/fi/uby37wt0izhce314g4j8v/radbug29.zip?rlkey=ddbi0bwmpfrpjv6wwgvib2032&dl=0

i still have this open and paused in vs, in case theres something i missed from the above zip that you would want?

**Comment by ryanfleury** [comment]
Can I also see VS with the locals of the debugger itself? Thanks!

**Comment by vfig** [comment]
![radbug29_vslocals](https://github.com/EpicGames/raddebugger/assets/81129/03f486d5-ebd4-4222-9000-fab757e1e969)

**Comment by ryanfleury** [comment]
Great, thanks. That’s probably the most I can ask for at this point—I’ll need to do a pass over this part of the control layer and prevent this sort of thing a priori. Thanks for the help!

**Comment by ryanfleury** [comment]
In theory this bug should be completely resolved as of d2d72bd7aba1de731ef1a11c0dc173f809368c8f, but short of doing a mathematical proof, this is one of those things that is just a matter of seeing how the theory matches up with actual battle testing. The stepping machine is complicated, so I could've made a mistake in my theory - so *please* re-open this issue if you hit this again.
