### ISSUE TITLE
`SetThreadDescription` doesn't appear to be respected

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EpicGames/raddebugger#3]
When launching my app it looks like only 2 threads have names in the debugger while we name all of our thread. Rust seems to be using the newer `SetThreadDescription` API rather then the older RaiseException method of naming threads, potentially this new api isn't yet supported?

**Comment by ryanfleury** [comment]
Yeah, as it turns out I was just working on this earlier, as this was a very quick request to come up :) I'll report back when the new Windows 10 thread names API is supported.

**Comment by ryanfleury** [comment]
This API is now supported as of e7243a2c2856494967aadd836778f14a913fa3f8. Let me know if you have further issues with this!
