### ISSUE TITLE
Add screenshots to the README

### ISSUE THREAD

**Issue by bbkane** [EpicGames/raddebugger#30]
I'd love some screenshots so I can see what this debugger looks like without having to install it

**Comment by bbkane** [comment]
@jeffrbig2 , you closed this ticket as "completed", but I don't see screenshots in the README

Was closing intentional (signifying y'all don't intend to add screenshots),  or am I missing something?

**Comment by jeffrbig2** [comment]
Because we don't need a reminder to add images some day.

**Comment by slonopotamus** [comment]
However potential users might want to have a reminder when that happens by subscribing to this issue...
