### ISSUE TITLE
macOS Build support

### ISSUE THREAD

**Issue by konsuko** [EpicGames/raddebugger#31]
Hello,

I know that not a *that many* people are making games on macOS, but I am one of them.
There is currently *no* good debugger that works on macOS, so the market is completely devoid of any alternatives to XCode and LLDB (which are both not comparable to this, I think).

RAD Debugger looks immensely useful, so I'd appreciate if Mac-Support could land on the roadmap some day (it probably isn't, currently). Also, I'd make the argument that if Linux is supported, (and that's not exactly used by many professional game devs as 90% are on Windows), Mac makes sense, too.

**Comment by emoon** [comment]
This is something I could potentially help out with. I think it makes sense to land Linux support first as some of the same functionality (such as memory, io, etc) can be shared with the macOS version.

**Comment by jeffrbig2** [comment]
Yeah, after Linux and after ARM64 on Win/Linux, we can start thinking about the macos plan.  I'll close this one for now.
