### ISSUE TITLE
The executable opens itself twice when the appdata/raddbg folder doesn't exist or is empty

### ISSUE THREAD

**Issue by longtran2904** [EpicGames/raddebugger#33]
If the `%appdata%/raddbg` folder doesn't exist or is empty, then when you open `raddbg.exe` (double-click or through the command line), it will open itself twice.

https://github.com/EpicGames/raddebugger/assets/53656110/975fc052-2999-4e2e-9a86-f7e47b6f4869

**Comment by ryanfleury** [comment]
Thanks for diagnosing this. Fixed in 0c497abba67f5606a1f992a741ec702284a6e976.
