### ISSUE TITLE
Strange value at the end of register view

### ISSUE THREAD

**Issue by emoon** [EpicGames/raddebugger#46]
At the end of the register view one can see a `00000`, `0000` value

![radbg_zero_end_register_view](https://github.com/EpicGames/raddebugger/assets/350822/3096111d-487b-4cbb-89ba-b8880bbd7917)

**Comment by ryanfleury** [comment]
Are there any specific circumstances under which you saw this show up? I don't see the same issue on my end.

**Comment by emoon** [comment]
Let me try to repro it. All I did was to debug raddbg and break in the debugger (I just picked any exe to try it out)

**Comment by ryanfleury** [comment]
Okay cool, thanks!
