### ISSUE TITLE
Can't see parent class members

### ISSUE THREAD

**Issue by ravencgg** [EpicGames/raddebugger#48]
I can view variables for the type itself, but it doesn't have information about the type that it inherits from. Just tested with latest code (1/15/2024).

![97201783-525d-4427-a905-839039257246](https://github.com/EpicGames/raddebugger/assets/1819790/162460e2-d2d1-4b1d-8c11-ce34eb661d70)

**Comment by MohitSethi99** [comment]
I'm using EASTL and facing the same issue, none of the data structures like eastl::string, eastl::vector, eastl::map shows anything as data lies in parent class/structs.

**Comment by ryanfleury** [comment]
Thanks for this report - I'll get this fixed.

**Comment by ryanfleury** [comment]
Single inheritance support is now in, as of c2e90225b90521782ea9b307dfb2b18f6d5b1cfc. Working on more complex cases now.

**Comment by ravencgg** [comment]
I just grabbed that commit and it's working for the list of variables in the child type, but accessing the member directly still says it can't be found.
![image](https://github.com/EpicGames/raddebugger/assets/1819790/44b30019-3d64-4401-93d7-dd42facbd72c)

**Comment by ryanfleury** [comment]
Shoot, thanks for catching that...

**Comment by ryanfleury** [comment]
Fixed that issue in e2e1382508385410dcb025d50dc644e0a2831a97 @ravencgg.
