### ISSUE TITLE
Access Violation while debugger exit

### ISSUE THREAD

**Issue by 1ndahous3** [EpicGames/raddebugger#5]
After various random steps in debugger I got the access violation crash while debugger exit.

![image](https://github.com/EpicGames/raddebugger/assets/9205230/1f11c98d-c02d-4203-a65a-def5e317c51e)

Seems like invalid `scratch` or `scratch.arena` value, but idk.

minidump: [raddbg.exe.31432.zip](https://github.com/EpicGames/raddebugger/files/13909141/raddbg.exe.31432.zip) (binary and pdb from "v0.9.0-alpha" release)

**Comment by ryanfleury** [comment]
Should be fixed in bcdc2f3026b88782665ba30650a5f4add98f0ea2 - let me know if this reoccurs.
