### ISSUE TITLE
Incorrect address shown in Memory View

### ISSUE THREAD

**Issue by emoon** [EpicGames/raddebugger#50]
![raddbg_incorrect_address](https://github.com/EpicGames/raddebugger/assets/350822/e69d26e3-2655-4080-8c33-f9864067e23d)

It looks like the top 32-bits gets cut off or something like that

**Comment by ryanfleury** [comment]
Oops! Fixed in 79677875c4ef0e9f2bb9f993a7fb4d4828ee0855.
