### ISSUE TITLE
Spaces are not correct and text file does not get updated on the debugger.

### ISSUE THREAD

**Issue by DevAgu93** [EpicGames/raddebugger#58]
Some spaces are wrong, and some changes aren't updated without restarting.

In the video I'm updating the spaces a bit and deleting some lines, then looking at the file in the debugger.

https://github.com/EpicGames/raddebugger/assets/63572671/350bff3b-c653-49fb-9c14-425c6bec35a8

**Comment by ryanfleury** [comment]
So, the spaces thing is just because I haven't implemented correct tab-layout yet (tabs just render as 1 space currently), but the not-reloading thing seems like a bug, for sure. Can you see if this issue is still happening as of 3567e6c53dac1a62d1c43032818fbc1385e8f731?

**Comment by DevAgu93** [comment]
It works now! 😄
