### ISSUE TITLE
due to some reason all the file content gets deleted when opened simultaneously in another editor.

### ISSUE THREAD

**Issue by kshanik** [EpicGames/raddebugger#63]
I do not have an exact way to reproduce it. Below is my setup:

Win 10
VS code for code editing
raddebugger for debugging

I have observed multiple times during last couple of days the file which i was debugging and at the same time when I try to edit inside VS code and try to save it gets me an warning of "content change from other process" to overwrite or not.

This was annoying as I lost couple of hours of work in between.

Below is the error in VS code while the same file was open in raddebugger.
![image](https://github.com/EpicGames/raddebugger/assets/1548915/f2cd6417-d723-4cf0-bfe3-6dd95778aadd)

It looks like intermittent.

**Comment by ryanfleury** [comment]
This should not occur as of 3567e6c53dac1a62d1c43032818fbc1385e8f731. Please reopen this issue if you continue seeing this issue.

**Comment by kshanik** [comment]
I tool the latest code and still able to reproduce this issue.

![image](https://github.com/EpicGames/raddebugger/assets/1548915/58f852fe-4028-4755-a4b4-e735ca486ae2)

**Comment by ryanfleury** [comment]
So, just to clarify, you saw *both* this error, *and* the "content change from other process" error, correct? RADDBG does not write anything to source files, so I would be surprised if VS Code was saying that there were changes, and if only VS Code and RADDBG were running. RADDBG *does* read source files, obviously, although it should be opening them up in shared mode, such that another process can still open & write to them. I may have made a mistake setting that up, so I will investigate further, but I am a little surprised (especially given that I have never seen this with my VS Code testing, or with other editors).

**Comment by kshanik** [comment]
It's fixed now on master. Thanks!
