### ISSUE TITLE
DAP (Debug Adapter Protocol) support

### ISSUE THREAD

**Issue by cristianadam** [EpicGames/raddebugger#66]
Having [DAP](https://microsoft.github.io/debug-adapter-protocol/) support would allow integration in other IDEs.

We at Qt Creator would love to have something fast for Windows. 

We currently support Python bindings for GDB, LLDB and the new DAP protocol. I think having DAP is easier than having Python support.

Microsoft contributed a [DAP debugger to CMake](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/8338) (the CMake code is BSD)

This would enable `raddebugger` to be used in Visual Studio via the [Visual Studio Debug Adapter Host](https://github.com/Microsoft/VSDebugAdapterHost) which has some value on its own.

**Comment by jeffrbig2** [comment]
We don't have any interest in integrating with other IDEs.
