### ISSUE TITLE
Cannot build from directory with spaces in path

### ISSUE THREAD

**Issue by gsbischoff** [EpicGames/raddebugger#7]
I tried building from a path that contained the directory `Downloaded Projects`. Doing so causes the file `base.natvis` to not be found with the error:
```
LINK : fatal error LNK1181: cannot open input file 'Projects\Raddbg\raddebugger\\src\natvis\base.natvis'
```
The build then fails.

**Comment by ryanfleury** [comment]
Fixed (by you!) in 7013797369ab4cc6425b6ffeeae483176c88cbee.
