### ISSUE TITLE
Build failure on EXCEPTION_POINTERS

### ISSUE THREAD

**Issue by kshanik** [EpicGames/raddebugger#78]
c:\dev\proj\raddebugger\src\raddbg\raddbg_main.cpp(113): error C2146: syntax error: missing ')' before identifier '_exception_info'
c:\dev\proj\raddebugger\src\raddbg\raddbg_main.cpp(113): error C3646: '_exception_info': unknown override specifier
c:\dev\proj\raddebugger\src\raddbg\raddbg_main.cpp(113): error C2059: syntax error: ')'
c:\dev\proj\raddebugger\src\raddbg\raddbg_main.cpp(296): error C2664: 'LPTOP_LEVEL_EXCEPTION_FILTER SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER)': cannot convert argument 1 from 'LONG (__cdecl *)(EXCEPTION_POINTERS *(__cdecl *)(_EXCEPTION_POINTERS *))' to 'LPTOP_LEVEL_EXCEPTION_FILTER'
c:\dev\proj\raddebugger\src\raddbg\raddbg_main.cpp(296): note: This conversion requires a reinterpret_cast, a C-style cast or function-style cast

Commit: 616897c8d6f6eba0640ba50b2de08c91870038a4 v0.9.5-alpha

**Comment by ryanfleury** [comment]
Looks like someone `#define`d `exception_info` in pre-2019 MSVC, then they reversed that decision later...

Anyway, should be fixed in e7046cb9d70679ef4570387813dd8325568113c4.
