### ISSUE TITLE
Viewing the address "0x-1" in the Memory View crashes the program

### ISSUE THREAD

**Issue by mistymntncop** [EpicGames/raddebugger#79]
Viewing the address "0x-1" in the Memory View crashes the program.

Steps to reproduce:
1. Open up memory view.
2. Alt+G (Go To Address)
3. Enter input "0x-1"

This results in the dialog box:
A fatal exception (code 0xc0000005) occurred. The process is terminating.

Press Ctrl+C to copy this text to clipboard, then create a new issue in
https://github.com/EpicGames/raddebugger/issues

Call stack:
0. [0x7ff6bd4e6c36] df_view_ui_Memory +28694, df_views.c line 8100
1. [0x7ff6bd51edc1] df_window_update_and_render +144577, df_gfx.c line 5567
2. [0x7ff6bd55b4a8] update_and_render +4056, raddbg.c line 259
3. [0x7ff6bd57276f] entry_point +5647, raddbg.c line 524
4. [0x7ff6bd3b245d] WinMain +877, raddbg_main.cpp line 348
5. [0x7ff6bd574382] __scrt_common_main_seh +262, exe_common.inl line 288
6. [0x7ffda4db7344] KERNEL32
7. [0x7ffda5b426b1] ntdll

**Comment by ryanfleury** [comment]
Fixed in 862ae81b0e08bb8a666447860adcff1fe52ba907.
