### ISSUE TITLE
Сlose tabs with middle mouse button

### ISSUE THREAD

**Issue by 1ndahous3** [EpicGames/raddebugger#80]
Support the widely used feature of closing tabs with a middle mouse button click.

**Comment by mmozeiko** [comment]
On TODO list here: https://github.com/EpicGames/raddebugger/blob/d172b3a059af35937b9cd7be5d73ceb35084c591/src/raddbg/raddbg.h#L251

**Comment by ryanfleury** [comment]
Done in 3a811e5e1633a463a7c4995db63ee6d206c495f9.
