### ISSUE TITLE
Windows Defender Detects Virus in v0.9.5-alpha Release

### ISSUE THREAD

**Issue by Husamdababneh** [EpicGames/raddebugger#82]
As the title said , Windows defender is detecting a Wacatac trojan horse in version v0.9.5-alpha
---
For me, I build the debugger from the source but, I think some people will just want to download and use it 

![chrome](https://github.com/EpicGames/raddebugger/assets/19290128/479f50ac-8d86-4680-90ba-28fe81f9dae9)

![windows](https://github.com/EpicGames/raddebugger/assets/19290128/5b24b665-ec4b-49d9-b3e8-80d34b435679)

---

**Comment by HACKE-RC** [comment]
![image](https://github.com/EpicGames/raddebugger/assets/60568652/ddb68f91-57d2-40c9-be91-9d822f51d040)
can confirm

**Comment by mmozeiko** [comment]
We're aware of this. See #19

**Comment by Husamdababneh** [comment]
Oh, Then I will close this issue since it's already known

@mmozeiko Thank you,
