### ISSUE TITLE
Cannot perform member access on this type

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGames/raddebugger#83]
Member access through references don't work
![image](https://github.com/EpicGames/raddebugger/assets/29519295/d6a5f28c-dea9-4c2d-9992-8a72da32788c)

**Comment by Husamdababneh** [comment]
@ryanfleury This also happens when trying to access a pointer, but dereferencing it and then access the members using '.' works

**Comment by ryanfleury** [comment]
Reproduced the reference `.` operator case, I must've broken this at some point... Fixing that now.

@Husamdababneh it should work on pointers. Can you be more specific about what you're seeing? Are your pointers modified in any way, e.g. `const` or `volatile`?

**Comment by ryanfleury** [comment]
Fixed accessing reference members in f11b128a07e251fa8f65e017f72d2e575007a6d4.

**Comment by ryanfleury** [comment]
Fixed constant pointer/reference member accesses in f75ee24a2b5e0b4316c6ea95c95a14ada36ebf29. Regular pointers should work, so I think I've addressed the bug you were referencing @Husamdababneh. Let me know if that is not the case.

**Comment by Husamdababneh** [comment]
@ryanfleury Yes It was actually const pointer, thank you 

This following image is just to make it clear for other readers (Watch window, last two lines)

![const_pointer_member_access](https://github.com/EpicGames/raddebugger/assets/19290128/232ecba3-537f-4f88-b225-6687e2954a9c)

**Comment by ryanfleury** [comment]
Cool. Yep, this should be fixed now.

**Comment by Husamdababneh** [comment]
@ryanfleury , I'm very sorry, but another thing I just noticed, dereferencing the pointer does not do anything 
---

![msvc-derefrence](https://github.com/EpicGames/raddebugger/assets/19290128/2d5c7f99-c24d-4767-9546-6d7f2cd5c1f5)

![rdbg-derefrence](https://github.com/EpicGames/raddebugger/assets/19290128/891b1cd4-b37d-4c4e-924a-5bc8445f8d5e)

**Comment by ryanfleury** [comment]
That should be fixed in 2a27b5af51fab3daea793beecdc1a1153db2d54d.
