### ISSUE TITLE
[Minor] Browse working directory UI doesn't work as expected

### ISSUE THREAD

**Issue by rtarun9** [EpicGames/raddebugger#85]
This is a *very minor bug*, where when adding / editing a target, when you use the UI to set the working directory you can mistakenly choose a file as the working directory as shown below:
![image](https://github.com/EpicGames/raddebugger/assets/75297835/1c83174a-6bd4-4b1e-8255-7efbe87505f1)

When this happens, the only way to correct the working directly is to 
(i) re-setup the target 
(ii) Manually enter the working directory path.

**Comment by ryanfleury** [comment]
I'll fix this, the directory picking is not great right now... But in the meantime, you shouldn't need to recreate the target, you can just edit the text after picking the file.

**Comment by rtarun9** [comment]
> I'll fix this, the directory picking is not great right now... But in the meantime, you shouldn't need to recreate the target, you can just edit the text after picking the file.

Not sure why I didn't try this out first, but editing the text works perfectly. Thanks for the info!
