### ISSUE TITLE
Updating a value via the Watch View is not Reflected in the Memory View

### ISSUE THREAD

**Issue by mistymntncop** [EpicGames/raddebugger#92]
When you manually update a value in the Watch View the updated value is not updated in the Memory View.

Steps to Reproduce:

1. Compile this C code:
```
#include <stdio.h>
#include <stdint.h>

int main(void) {
    uint32_t values[] = {
        1,2,3,4,5
    };
    int set_a_break_here = 3;
    return 0;
}
```
2. Set a breakpoint on "set_a_break_here" line
3. Open Memory View and Go To Memory "&values"
4. View "values" in Watch View and modify values[0] to be 0x1337

The updated value will not be shown in the Memory View. The value of values[0] is still shown as "1" in the Memory View.

**Comment by ryanfleury** [comment]
Fixed in e222996b1969d17bf0577358c540cfb651e56ee7.
