### ISSUE TITLE
PDB to RADDBG producing empty .raddbg files

### ISSUE THREAD

**Issue by tim-rex** [EpicGames/raddebugger#95]
I don't have a minimal repro for this, but I have a project that appears to be producing invalid raddbg files (zero bytes).

My applications consists of an .exe and a .dll
Debug sessions show local functions as `[external code]` and I'm unable to navigate to source code

![image](https://github.com/EpicGames/raddebugger/assets/19639392/943704ec-acc9-46b6-9863-19d14e5d6a85)

Here's my session fwiw
![image](https://github.com/EpicGames/raddebugger/assets/19639392/126f8f59-b66e-4870-a4fc-2bdbfb5ca1d5)

Here's my PDB's and the associated RADDBG files.
![image](https://github.com/EpicGames/raddebugger/assets/19639392/5ac9eecd-b065-4314-a2a8-fbcc3df4bc26)

Are there any diagnostics/logs I can provide to account for the raddbg files being empty?

**Comment by ryanfleury** [comment]
Right now, there aren't any diagnostics/logs that you'd be able to send that'd help with this (if you cannot send the actual EXEs/DLLs/PDBs), but one thing that'd help is knowing how you're building your EXE/DLLs. What language, what compiler flags, what linker flags, what compiler/linker (& versions), and so on. That might be enough to lead me to a repro case.

**Comment by mmozeiko** [comment]
It is possible that converter crashed. But because of `--quiet` flag there's no exception message box.

You can try running converter standalone and see if some crash shows up:
```
raddbg.exe --convert -out:Offworld.raddbg -exe:Offworld.exe -pdb:Offworld.pdb
```
Preferably on debug build, so asserts are enabled.

**Comment by tim-rex** [comment]
I'll see if I can work up a minimal repro first, probably a lot easier if I can send you executables + pdb's if not a complete VS solution.

Until then..  C++ built with VS 2022

Build options for the primar executable:
```
/JMC /ifcOutput "builds\Windows_x64\Debug\Offworld\" /FR"builds\Windows_x64\Debug\Offworld\" /GS /W3 /Zc:wchar_t  /Zi /Gm- /Od /sdl- /Fd"builds\Windows_x64\Debug\Offworld\vc143.pdb" /Zc:inline /fp:fast /D "_UNICODE" /D "UNICODE" /D "IMGUI_USER_CONFIG=\"custom_imgui_config.h\"" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /showIncludes /MDd /std:c++17 /FC /Fa"builds\Windows_x64\Debug\Offworld\" /nologo /Fo"builds\Windows_x64\Debug\Offworld\" /Fp"builds\Windows_x64\Debug\Offworld\Offworld.pch" /diagnostics:column 
```

Linker options for the executable:
```
/OUT:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld.exe" /MANIFEST /NXCOMPAT /PDB:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /DEBUG:FASTLINK /MACHINE:X64 /INCREMENTAL /PGD:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld.pgd" /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"builds\Windows_x64\Debug\Offworld\Offworld.exe.intermediate.manifest" /LTCGOUT:"builds\Windows_x64\Debug\Offworld\Offworld.iobj" /MAP /ERRORREPORT:PROMPT /ILK:"builds\Windows_x64\Debug\Offworld\Offworld.ilk" /NOLOGO /LIBPATH:"C:\Program Files (x86)\Audiokinetic\Wwise 2022.1.4.8202\SDK\x64_vc170\Debug\lib" /LIBPATH:"C:\VulkanSDK\1.3.268.0\Lib" /TLBID:1 
```

Build options for the DLL
```
/JMC /permissive /ifcOutput "builds\Windows_x64\Debug\Offworld Core DLL\" /FR"builds\Windows_x64\Debug\Offworld Core DLL\" /GS /W3 /Zc:wchar_t  /Zi /Gm- /Od /sdl /Fd"builds\Windows_x64\Debug\Offworld Core DLL\vc143.pdb" /Zc:inline /fp:fast  /D "IMGUI_USER_CONFIG=\"custom_imgui_config.h\"" /D "_DEBUG" /D "OFFWORLDCOREDLL_EXPORTS" /D "_WINDOWS" /D "_USRDLL" /D "_WINDLL" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /showIncludes /MDd /std:c++17 /FC /Fa"builds\Windows_x64\Debug\Offworld Core DLL\" /nologo /Fo"builds\Windows_x64\Debug\Offworld Core DLL\" /diagnostics:column 
```

Linker options for the DLL
```
/OUT:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld Core DLL.dll" /MANIFEST /NXCOMPAT /PDB:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld Core DLL-18_10_42_237.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "comdlg32.lib" "advapi32.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "odbc32.lib" "odbccp32.lib" /IMPLIB:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld Core DLL.lib" /DEBUG:FASTLINK /DLL /MACHINE:X64 /INCREMENTAL /PGD:"C:\Users\Tim Kane\Documents\Visual Studio 2017\Projects\Offworld\builds\Windows_x64\Debug\Offworld Core DLL.pgd" /SUBSYSTEM:WINDOWS /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"builds\Windows_x64\Debug\Offworld Core DLL\Offworld Core DLL.dll.intermediate.manifest" /LTCGOUT:"builds\Windows_x64\Debug\Offworld Core DLL\Offworld Core DLL.iobj" /MAP /ERRORREPORT:PROMPT /ILK:"builds\Windows_x64\Debug\Offworld Core DLL\Offworld Core DLL.ilk" /NOLOGO /LIBPATH:"C:\Program Files (x86)\Audiokinetic\Wwise 2022.1.4.8202\SDK\x64_vc170\Debug\lib" /LIBPATH:"C:\VulkanSDK\1.3.268.0\Lib" /TLBID:1 
```

Note the PDB filename for the DLL is generated at built time. I don't believe this to be related, rad appears to be picking up the correct pdb.

**Comment by ryanfleury** [comment]
So, one thing I see immediately is `/DEBUG:FASTLINK`, which leaves all of the "meat" of debug info in the OBJ files, and puts almost nothing into the PDBs. This is not supported by RADDBG right now, and I believe not recommended by Microsoft anymore these days. Do you see different results with that option removed?

**Comment by tim-rex** [comment]
One quick observation..  Release build seems better, as does a Clang (debug) build.
Definitely isolated to the MSVC debug build (for which the above provided build options apply).

**Comment by tim-rex** [comment]
> So, one thing I see immediately is `/DEBUG:FASTLINK`, which leaves all of the "meat" of debug info in the OBJ files, and puts almost nothing into the PDBs. This is not supported by RADDBG right now, and I believe not recommended by Microsoft anymore these days. Do you see different results with that option removed?

Bingo. Changing to `/DEBUG` appears to have resolved it.
Thanks @ryanfleury

**Comment by tim-rex** [comment]
Happy to close this out unless you think there is merit in trying to detect this situation and provide user feedback in some way.

**Comment by ryanfleury** [comment]
No problem! Yeah, we already know about this issue, so I think we can close this one. I've not come up with any detection/feedback mechanisms for this yet, but I've put down in my notes to investigate this, since feedback would be more ideal than silent failure.

**Comment by tim-rex** [comment]
For reference..
https://learn.microsoft.com/en-us/cpp/build/reference/debug-generate-debug-info?view=msvc-170

> Since Visual Studio 2019, /DEBUG:FULL linking times have improved significantly, and /DEBUG:FASTLINK isn't always faster than /DEBUG:FULL. Since /DEBUG:FASTLINK no longer provides large build time improvements and results in a slower debugging experience versus /DEBUG:FULL, this option is no longer recommended.


Interestingly, that page also notes a tool that can be used to construct a full PDB from a FASTLINK build using `mspdbcmf.exe`, if that helps in any way.

**Comment by ryanfleury** [comment]
> Since Visual Studio 2019, /DEBUG:FULL linking times have improved significantly

I wonder if that has to do with their "optimization" of [not removing stale type info](https://www.computerenhance.com/p/msvc-pdbs-are-filled-with-stale-debug) in PDBs... and if they measured the linking time after one PDB has been used for a very long time...

**Comment by tim-rex** [comment]
It was that very article that drew my attention to this project so.. go microsoft!
