### ISSUE TITLE
Output pane shows no debug output

### ISSUE THREAD

**Issue by tim-rex** [EpicGames/raddebugger#96]
I presume the output pane would emit the usual debug output from the likes of `OutputDebugString` and friends
I've tried various debug sessions of various applications, I'm unable to elicit any output whatsoever.

I've thrown together the attached minimal repro, not much to it.
[OutputDebugStringConsole.zip](https://github.com/EpicGames/raddebugger/files/14000649/OutputDebugStringConsole.zip)

![image](https://github.com/EpicGames/raddebugger/assets/19639392/fa5857e7-3066-46fb-b4ee-dc1b011a56c9)

**Comment by ryanfleury** [comment]
Hm, looks like I recently broke this, I'll investigate...

**Comment by ryanfleury** [comment]
Fixed as of fb7db066719bfd367ee91a11b2eaed785c857048.
