### ISSUE TITLE
Doesn't work well with debugging Chromium

### ISSUE THREAD

**Issue by justanotheranonymoususer** [EpicGames/raddebugger#99]
I built Chromium (https://chromium.googlesource.com/chromium/src/+/HEAD/docs/windows_build_instructions.md) and tried to use raddebugger for debugging it. I wondered how it will be comparing to vscode debugging. raddebugger doesn't feel stable, it either hangs, crashes, or shows OOM error. I think this is a good stress test for the debugger. Looking forward when it becomes more stable, looks really promising!

**Comment by ryanfleury** [comment]
Yeah this is known & on the list. We've designed the debugger to allow for e.g. UE and Chrome debugging, so we'll get there hopefully later in the alpha, just a matter of maturity, battle testing, and ironing out the most major issues.
